export const NEW_NOTE_REQUEST = "NEW_NOTE_REQUEST"
export const NEW_NOTE_SUCCESS = "NEW_NOTE_SUCCESS"
export const NEW_NOTE_FAIL = "NEW_NOTE_FAIL"

export const ALL_NOTES_REQUEST = "ALL_NOTES_REQUEST"
export const ALL_NOTES_SUCCESS = "ALL_NOTES_SUCCESS"
export const ALL_NOTES_FAIL = "ALL_NOTES_FAIL"

export const ONE_NOTE_REQUEST = "ONE_NOTE_REQUEST"
export const ONE_NOTE_SUCCESS = "ONE_NOTE_SUCCESS"
export const ONE_NOTE_FAIL = "ONE_NOTE_FAIL"

export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST"
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS"
export const UPDATE_NOTE_FAIL = "UPDATE_NOTE_FAIL"

export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST"
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS"
export const DELETE_NOTE_FAIL = "DELETE_NOTE_FAIL"
export const DELETE_NOTE_RESET = "DELETE_NOTE_RESET"


export const CLEAR_ERRORS = "CLEAR_ERRORS"